### ISSUE TITLE
No bin/as/as.vax/astoks.H

### ISSUE THREAD

**Issue by b4** [abs0/4.3BSD-Quasijarus#1]
File not present - `make depend` fails without it. astoks.h and astoks.H are not the same file.

**Comment by abs0** [comment]
Are you on a case insensitive filesystem (MacOS)?

You need to checkout on a case sensitive filesystem (will update readme)

**Comment by b4** [comment]
That would do it - forgot my filesystem is case insensitive.

**Comment by abs0** [comment]
Glad its resolved - have added a note to the README :)

David
