### ISSUE TITLE
Build failure: libc

### ISSUE THREAD

**Issue by b4** [abs0/4.3BSD-Quasijarus#2]
(cd ../library; rm -f  clrerr.o doprnt.o doscan.o exit.o fdopen.o fgetc.o filbuf.o  findiop.o flsbuf.o fopen.o fprintf.o fputc.o fread.o freopen.o  fseek.o ftell.o fwrite.o getchar.o getw.o printf.o putchar.o  putw.o rew.o scanf.o setbuf.o setbuffer.o sprintf.o ungetc.o  vfprintf.o vprintf.o vsprintf.o )
(cd ../profiled; rm -f  clrerr.o doprnt.o doscan.o exit.o fdopen.o fgetc.o filbuf.o  findiop.o flsbuf.o fopen.o fprintf.o fputc.o fread.o freopen.o  fseek.o ftell.o fwrite.o getchar.o getw.o printf.o putchar.o  putw.o rew.o scanf.o setbuf.o setbuffer.o sprintf.o ungetc.o  vfprintf.o vprintf.o vsprintf.o )
ln  clrerr.o doprnt.o doscan.o exit.o fdopen.o fgetc.o filbuf.o  findiop.o flsbuf.o fopen.o fprintf.o fputc.o fread.o freopen.o  fseek.o ftell.o fwrite.o getchar.o getw.o printf.o putchar.o  putw.o rew.o scanf.o setbuf.o setbuffer.o sprintf.o ungetc.o  vfprintf.o vprintf.o vsprintf.o  ../library
(cd profiled; ln  clrerr.o doprnt.o doscan.o exit.o fdopen.o fgetc.o filbuf.o  findiop.o flsbuf.o fopen.o fprintf.o fputc.o fread.o freopen.o  fseek.o ftell.o fwrite.o getchar.o getw.o printf.o putchar.o  putw.o rew.o scanf.o setbuf.o setbuffer.o sprintf.o ungetc.o  vfprintf.o vprintf.o vsprintf.o  ../../profiled)
cd cal; make  DEFS="-DLIBC_SCCS -DSYSLIBC_SCCS" link
ld:profiled/asctime.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c asctime.c
ld:profiled/ctime.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c ctime.c
ld:profiled/gmtime.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c gmtime.c
ld:profiled/localtime.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c localtime.c
ld:profiled/mjd2greg.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c mjd2greg.c
ld:profiled/sexatime.o: No such file or directory
*** Exit 4 (ignored)
cc -O -R -DLIBC_SCCS -DSYSLIBC_SCCS -c sexatime.c
(cd ../library; rm -f asctime.o ctime.o gmtime.o localtime.o mjd2greg.o sexatime.o)
(cd ../profiled; rm -f asctime.o ctime.o gmtime.o localtime.o mjd2greg.o sexatime.o)
ln asctime.o ctime.o gmtime.o localtime.o mjd2greg.o sexatime.o ../library
(cd profiled; ln asctime.o ctime.o gmtime.o localtime.o mjd2greg.o sexatime.o ../../profiled)
sh: profiled: bad directory
*** Exit 1

Seems lib/libc's subdirectory Makefiles expect something incorrect about the profiled/ directory

**Comment by abs0** [comment]
Thanks for the fix
